# Imagen base
FROM node:14

# Directorio de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY NewsletterBuddyBackend/package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar el resto del código fuente
COPY NewsletterBuddyBackend/src ./src

# Compilar TypeScript a JavaScript
RUN npm run build

# Exponer el puerto en el que se ejecutará el backend
EXPOSE 3000

# Comando para iniciar el servidor
CMD ["npm", "start"]
